### ISSUE TITLE
Running PlanningPoker

### ISSUE THREAD

**Issue by Jero8i** [qJake/planning-poker#1]
Hi qJake,

I´m really new on this and I want to run the planningpoker.
I guess that I missing something I followed your setps, now I have the client running but I cannot connect to server.

![image](https://f.cloud.github.com/assets/5394201/2459775/12ae0d46-af61-11e3-964d-0d9e543033a3.png)

I also tried to browse the PokerServerManager but I´m getting the following error:

```
Server Error in '/' Application.

Parser Error

Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Could not load type 'PokerServerManager.Global'.

Source Error: 

Line 1:  <%@ Application Codebehind="Global.asax.cs" Inherits="PokerServerManager.Global" Language="C#" %>
```

Could you help me?

Thanks!

Jeronimo

**Comment by qJake** [comment]
Follow-up: I believe #2 was the same problem, and has since been resolved (via commit 3f07f8b96b1916d63498908f486a93ead1749120).
