### ISSUE TITLE
Error when accessing PokerServerManager

### ISSUE THREAD

**Issue by Demian87** [qJake/planning-poker#2]
I Followed all the instructions and all three project built successfully.
When going to localhost/PokerWebClient/ I'm getting a client, which can not get the list of servers
When going to localhost/PokerServerManager I\m getting the following error:
Parser Error Message: Could not load type 'PokerServerManager.Global'.
Line 1:  <%@ Application Codebehind="Global.asax.cs" Inherits="PokerServerManager.Global" Language="C#" %>

What am I doing wrong?

**Comment by Demian87** [comment]
Had to change namespace to PokerServerManager in Global and _Default

**Comment by qJake** [comment]
Hey @Demian87, glad you got it fixed. Would you mind sending a pull request over to fix that? Thanks!
